---
title: "HW 5 GOOG"
Author: "Hunter Hostage"
output: html_notebook
---
# Homework 5

## Part I
```{r}
rankcor <- function(x, y){
  n <- length(x)
  # Sets length of n to x
  stopifnot(length(y) == n)
  #Stops function if length of y is not equal to length of n
  x.ranks <- rank(x)
  #
  y.ranks <- rank(y)
  #
  mean.x <- mean(x.ranks)
  #
  mean.y <- mean(y.ranks)
  #
  covariance.term <- cov(x.ranks - mean.x, y - mean.y)
  #
  sd.x <- sd(x.ranks)
  #
  sd.y <- sd(y.ranks)
  #
  rank.cor <- covariance.term / (sd.x*sd.y)
  #
  return(rank.cor)
}
```

### 1


### 2
```{r}
x=c(2,4,6,8)
y= c(64,36,16,4)
rankcor(x,y)
```
I get a value of -20. 

### 3
1. Value is incorrect because it is not within -1-1. 

2.

### 4
```{r}
x.new= c(4,5,6,7)
y.new= c(4,5,6,7)

rankcor(x.new,y.new)
```


## Part II

### 5
```{r}
testrankcor=function( FUN=rankcor){
  x= c(2,4,6,8)
  y= c(64,36,16,4)

  x.new= c(4,5,6,7)
  y.new= c(4,5,6,7)
  
  rankcor.first= rankcor(x,y)
  rankcor.second= rankcor(x.new,y.new)
  
  if(isTRUE(all.equal(rankcor.first,-1))){
    if(isTRUE(all.equal(rankcor.second,1))){
      return(TRUE)
    }else{ warning( "Problem 4 Vectors Do not Pass")}
  }else{ warning("Problem 2 Vector Do not Pass")}
}
testrankcor()
```

### 6
```{r}
rankcor <- function(x, y){
  browser()
  n <- length(x)
  stopifnot(length(y) == n)
  
  x.ranks <- rank(x)
  y.ranks <- rank(y)
  
  mean.x <- mean(x.ranks)
  mean.y <- mean(y.ranks)
  
  covariance.term <- cov(x.ranks - mean.x, y - mean.y)
  
  sd.x <- sd(x.ranks)
  sd.y <- sd(y.ranks)
  
  rank.cor <- covariance.term / (sd.x*sd.y)
  
  return(rank.cor)
}
```
When assigning the covariance term, the function is using y, not y.ranks.

### 7

## Part III

### 8

### 9

### 10
